"""PRIN -- Phase-Resonance Interference Network.

Public Python API for PRIN, the from-scratch rebuild of PRINet 3.0. The
numerical core lives in the compiled Rust extension ``prin._prin_core``; this
package holds API ergonomics, PyTorch bridges, plotting, and orchestration
only (no numerics -- see the Target Architecture design rules in
``DOCS/PRIN_Project_Plan.md``).

Subpackages:
    prin.dynamics: oscillator state, models, integrators, coupling, PAC.
    prin.dlpack: zero-copy DLPack tensor exchange between PyTorch and the
    PRIN Rust core.
    prin.metrics: synchronization, coherence, spectral, energy, and chimera
    metrics.
    prin.nn: torch.nn.Module wrappers, autograd.Function bridges, baselines.
    prin.train: Rust-native trainable-stack orchestration entry points
    (temporal CLEVR-N training pipeline).
    prin.daemon: subconscious controller -- ONNX inference, execution-provider
    selection (VitisAI -> DirectML -> CPU), and model validation.
    prin.eval: MOT evaluation and temporal metrics.
    prin.experiments: ablation, stats, adversarial, and training frameworks.
    prin.parity: golden-trajectory corpus, manifest/loader, and differential
    harness for numerical parity against PRINet 3.0.
    prin.reporting: benchmark JSON reports, figures, tables, profiler.
"""

from __future__ import annotations

from prin._compat import (
    BackendUnavailableError,
    DeltaThetaGammaNetwork,
    OscillatorModel,
    RIPOptimizer,
    SCALROptimizer,
    SynchronizedGradientDescent,
    TemporalPhasePropagator,
    ThetaGammaNetwork,
    cuda_fused_kernel_available,
    fused_discrete_step_cuda,
    temporal_recovery_speed,
    triton_available,
    triton_fused_discrete_step,
    triton_fused_mean_field_rk4_step,
    triton_hierarchical_order_param,
    triton_pac_modulation,
    triton_sparse_knn_coupling,
)
from prin.daemon import (
    CONTROL_DIM,
    STATE_DIM,
    BackendType,
    ControlSignals,
    SubconsciousController,
    SubconsciousDaemon,
    SubconsciousState,
    backend_info,
    create_session,
    detect_best_backend,
    directml_available,
    npu_available,
)
from prin.dynamics import (
    ExponentialIntegrator,
    HopfOscillator,
    KuramotoOscillator,
    MultiRateIntegrator,
    OscillatorState,
    PhaseAmplitudeCoupling,
    StuartLandauOscillator,
)
from prin.eval import (
    TemporalMetrics,
    binding_robustness_score,
    compute_full_temporal_metrics,
    identity_overcount,
    identity_switches,
    mostly_tracked_lost,
    temporal_smoothness,
    track_duration_stats,
    track_fragmentation_rate,
)
from prin.experiments import compute_p_value
from prin.kernels import (
    build_knn_neighbors,
    csr_coupling_step,
    detect_oscillation,
    phase_to_rate,
    pytorch_cross_band_coupling,
    pytorch_fused_discrete_step,
    pytorch_fused_discrete_step_full,
    pytorch_fused_sub_step_rk4,
    pytorch_hierarchical_order_param,
    pytorch_mean_field_rk4_step,
    pytorch_multi_rate_derivatives,
    pytorch_multi_rate_rk4_step,
    pytorch_pac_modulation,
    pytorch_sparse_knn_coupling,
    sparse_coupling_matrix,
    sparse_coupling_matrix_csr,
    sparse_knn_coupling_step,
    sweep_coupling_params,
)
from prin.metrics import (
    bimodality_index,
    build_phase_knn,
    inter_frame_phase_correlation,
    kuramoto_order_parameter,
    local_order_parameter,
    mean_phase_coherence,
    phase_coherence_matrix,
    sparse_mean_phase_coherence,
    sparse_synchronization_energy,
)
from prin.nn import (
    AlternatingOptimizer,
    DenseAutoencoder,
    DentateGyrusConverter,
    DGLayer,
    DiscreteDeltaThetaGamma,
    DiscreteDeltaThetaGammaLayer,
    FeedbackInhibition,
    FeedforwardInhibition,
    GatedPhaseActivation,
    HierarchicalResonanceLayer,
    HolomorphicActivation,
    HolomorphicEnergy,
    HolomorphicEPTrainer,
    HybridCLEVRN,
    HybridPRINet,
    HybridPRINetV2,
    HybridPRINetV2CLEVRN,
    InterleavedHybridPRINet,
    OscillatoryAttention,
    PhaseActivation,
    PhaseAmplitudeCouplingLayer,
    PhaseToRateAutoencoder,
    PhaseToRateConverter,
    PhaseTracker,
    PhaseTrackerFrozen,
    PhaseTrackerStatic,
    PRINetModel,
    ResonanceLayer,
    SlotAttentionCLEVRN,
    SlotAttentionFrozen,
    SlotAttentionModule,
    SlotAttentionNoGRU,
    SparsityRegularizationLoss,
    TemporalHybridPRINet,
    TemporalSlotAttentionMOT,
    compile_model,
    dSiLU,
    oscillatory_weight_init,
)
from prin.reporting import (
    configure_neurips_style,
    fig_ablation_results,
    fig_chimera_heatmap,
    fig_clevr_n_capacity,
    fig_gold_standard_chimera,
    fig_mot_identity_preservation,
    fig_oscillosim_scaling,
    fig_parameter_efficiency,
    fig_statistical_summary,
    fig_training_curves,
    generate_all_figures,
    generate_all_tables,
    generate_benchmark_report,
    generate_leaderboard,
    generate_scalr_metrics_report,
    table_ablation_variants,
    table_chimera_gold_standard,
    table_occlusion_sweep,
    table_oscillosim_scaling,
    table_parameter_efficiency,
    table_statistical_summary,
)
from prin.simulation import (
    LargeScaleOscillatorSystem,
    OscillatorPruner,
    OscilloSim,
    SimulationResult,
    quick_simulate,
)
from prin.solvers import (
    BatchedRK45Solver,
    FixedStepRK4Solver,
    SolverResult,
    gradient_checkpoint_integration,
)
from prin.temporal_training import (
    MultiSeedResult,
    SequenceData,
    TemporalTrainer,
    TrainingSnapshot,
    count_parameters,
    generate_dataset,
    generate_temporal_clevr_n,
    hungarian_similarity_loss,
    temporal_smoothness_loss,
    train_multi_seed,
)
from prin.tensor import CPDecomposition, PolyadicTensor
from prin.topology import ring_topology, small_world_topology
from prin.train import TrainingResult
from prin.training_hooks import (
    ActiveControlTrainer,
    AsyncCPUGPUPipeline,
    ControlSignalBuffer,
    MixedPrecisionTrainer,
    StateCollector,
    TelemetryLogger,
    collect_system_state,
    create_ablation_tracker,
    retrain_controller,
)
from prin.y4q1_tools import (
    AblationConfig,
    AblationHybridPRINetV2,
    ExtendedTrainingResult,
    count_flops,
    create_ablation_model,
    measure_wall_time,
    train_clevr_n_extended,
    train_clevr_n_single_seed,
)

__version__ = "0.3.0-alpha.1"

try:
    from prin._prin_core import core_version
except ImportError as _exc:  # pragma: no cover - build-environment guard
    raise ImportError(
        "The compiled PRIN core extension (prin._prin_core) is not available. "
        "Build it with: maturin develop -m crates/prin-py/Cargo.toml"
    ) from _exc

__all__ = [
    "CONTROL_DIM",
    "STATE_DIM",
    "AblationConfig",
    "AblationHybridPRINetV2",
    "ActiveControlTrainer",
    "AlternatingOptimizer",
    "AsyncCPUGPUPipeline",
    "BackendType",
    "BackendUnavailableError",
    "BatchedRK45Solver",
    "CPDecomposition",
    "ControlSignalBuffer",
    "ControlSignals",
    "DGLayer",
    "DeltaThetaGammaNetwork",
    "DenseAutoencoder",
    "DentateGyrusConverter",
    "DiscreteDeltaThetaGamma",
    "DiscreteDeltaThetaGammaLayer",
    "ExponentialIntegrator",
    "ExtendedTrainingResult",
    "FeedbackInhibition",
    "FeedforwardInhibition",
    "FixedStepRK4Solver",
    "GatedPhaseActivation",
    "HierarchicalResonanceLayer",
    "HolomorphicActivation",
    "HolomorphicEPTrainer",
    "HolomorphicEnergy",
    "HopfOscillator",
    "HybridCLEVRN",
    "HybridPRINet",
    "HybridPRINetV2",
    "HybridPRINetV2CLEVRN",
    "InterleavedHybridPRINet",
    "KuramotoOscillator",
    "LargeScaleOscillatorSystem",
    "MixedPrecisionTrainer",
    "MultiRateIntegrator",
    "MultiSeedResult",
    "OscillatorModel",
    "OscillatorPruner",
    "OscillatorState",
    "OscillatoryAttention",
    "OscilloSim",
    "PRINetModel",
    "PhaseActivation",
    "PhaseAmplitudeCoupling",
    "PhaseAmplitudeCouplingLayer",
    "PhaseToRateAutoencoder",
    "PhaseToRateConverter",
    "PhaseTracker",
    "PhaseTrackerFrozen",
    "PhaseTrackerStatic",
    "PolyadicTensor",
    "RIPOptimizer",
    "ResonanceLayer",
    "SCALROptimizer",
    "SequenceData",
    "SimulationResult",
    "SlotAttentionCLEVRN",
    "SlotAttentionFrozen",
    "SlotAttentionModule",
    "SlotAttentionNoGRU",
    "SolverResult",
    "SparsityRegularizationLoss",
    "StateCollector",
    "StuartLandauOscillator",
    "SubconsciousController",
    "SubconsciousDaemon",
    "SubconsciousState",
    "SynchronizedGradientDescent",
    "TelemetryLogger",
    "TemporalHybridPRINet",
    "TemporalMetrics",
    "TemporalPhasePropagator",
    "TemporalSlotAttentionMOT",
    "TemporalTrainer",
    "ThetaGammaNetwork",
    "TrainingResult",
    "TrainingSnapshot",
    "__version__",
    "backend_info",
    "bimodality_index",
    "binding_robustness_score",
    "build_knn_neighbors",
    "build_phase_knn",
    "collect_system_state",
    "compile_model",
    "compute_full_temporal_metrics",
    "compute_p_value",
    "configure_neurips_style",
    "core_version",
    "count_flops",
    "count_parameters",
    "create_ablation_model",
    "create_ablation_tracker",
    "create_session",
    "csr_coupling_step",
    "cuda_fused_kernel_available",
    "dSiLU",
    "detect_best_backend",
    "detect_oscillation",
    "directml_available",
    "fig_ablation_results",
    "fig_chimera_heatmap",
    "fig_clevr_n_capacity",
    "fig_gold_standard_chimera",
    "fig_mot_identity_preservation",
    "fig_oscillosim_scaling",
    "fig_parameter_efficiency",
    "fig_statistical_summary",
    "fig_training_curves",
    "fused_discrete_step_cuda",
    "generate_all_figures",
    "generate_all_tables",
    "generate_benchmark_report",
    "generate_dataset",
    "generate_leaderboard",
    "generate_scalr_metrics_report",
    "generate_temporal_clevr_n",
    "gradient_checkpoint_integration",
    "hungarian_similarity_loss",
    "identity_overcount",
    "identity_switches",
    "inter_frame_phase_correlation",
    "kuramoto_order_parameter",
    "local_order_parameter",
    "mean_phase_coherence",
    "measure_wall_time",
    "mostly_tracked_lost",
    "npu_available",
    "oscillatory_weight_init",
    "phase_coherence_matrix",
    "phase_to_rate",
    "pytorch_cross_band_coupling",
    "pytorch_fused_discrete_step",
    "pytorch_fused_discrete_step_full",
    "pytorch_fused_sub_step_rk4",
    "pytorch_hierarchical_order_param",
    "pytorch_mean_field_rk4_step",
    "pytorch_multi_rate_derivatives",
    "pytorch_multi_rate_rk4_step",
    "pytorch_pac_modulation",
    "pytorch_sparse_knn_coupling",
    "quick_simulate",
    "retrain_controller",
    "ring_topology",
    "small_world_topology",
    "sparse_coupling_matrix",
    "sparse_coupling_matrix_csr",
    "sparse_knn_coupling_step",
    "sparse_mean_phase_coherence",
    "sparse_synchronization_energy",
    "sweep_coupling_params",
    "table_ablation_variants",
    "table_chimera_gold_standard",
    "table_occlusion_sweep",
    "table_oscillosim_scaling",
    "table_parameter_efficiency",
    "table_statistical_summary",
    "temporal_recovery_speed",
    "temporal_smoothness",
    "temporal_smoothness_loss",
    "track_duration_stats",
    "track_fragmentation_rate",
    "train_clevr_n_extended",
    "train_clevr_n_single_seed",
    "train_multi_seed",
    "triton_available",
    "triton_fused_discrete_step",
    "triton_fused_mean_field_rk4_step",
    "triton_hierarchical_order_param",
    "triton_pac_modulation",
    "triton_sparse_knn_coupling",
]
