"""Type stubs for the compiled PRIN core extension (``prin._prin_core``).

Regenerated as the Rust API grows; keep in sync with ``crates/prin-py``.
"""

__version__: str

def core_version() -> str: ...
def dlpack_negate(obj: object) -> object: ...
def dlpack_negate_batched(tensors: list[object]) -> list[object]: ...
def dlpack_round_trip(obj: object) -> object: ...
