"""Canonical PRIN RC1 top-level public API names.

The tuple is the single source used by both ``prin.__all__`` and the frozen API
contract. WP-036 sub-passes extend it as additional compatibility symbols land.
"""

from __future__ import annotations

RC1_PUBLIC_API: tuple[str, ...] = (
    "__version__",
    "core_version",
    "OscillatorState",
    "KuramotoOscillator",
    "StuartLandauOscillator",
    "HopfOscillator",
    "ExponentialIntegrator",
    "kuramoto_order_parameter",
    "mean_phase_coherence",
    "phase_coherence_matrix",
    "build_phase_knn",
    "sparse_mean_phase_coherence",
    "sparse_synchronization_energy",
    "PhaseAmplitudeCoupling",
    "MultiRateIntegrator",
    "ResonanceLayer",
    "GatedPhaseActivation",
    "generate_benchmark_report",
    "generate_leaderboard",
    "generate_scalr_metrics_report",
    "SubconsciousState",
    "ControlSignals",
    "STATE_DIM",
    "CONTROL_DIM",
    "SubconsciousDaemon",
    "SubconsciousController",
    "BackendType",
    "detect_best_backend",
    "npu_available",
    "directml_available",
    "create_session",
    "backend_info",
    "OscillatoryAttention",
    "inter_frame_phase_correlation",
    "HybridPRINetV2",
    "PhaseTracker",
    "SlotAttentionModule",
    "TemporalSlotAttentionMOT",
    "local_order_parameter",
    "bimodality_index",
    "compute_p_value",
    "PhaseTrackerFrozen",
    "PhaseTrackerStatic",
    "SlotAttentionNoGRU",
    "SlotAttentionFrozen",
    "TemporalMetrics",
    "temporal_smoothness",
    "identity_switches",
    "track_fragmentation_rate",
    "identity_overcount",
    "mostly_tracked_lost",
    "track_duration_stats",
    "binding_robustness_score",
    "compute_full_temporal_metrics",
    "TrainingResult",
    "configure_neurips_style",
    "fig_clevr_n_capacity",
    "fig_chimera_heatmap",
    "fig_mot_identity_preservation",
    "fig_oscillosim_scaling",
    "fig_ablation_results",
    "fig_parameter_efficiency",
    "fig_training_curves",
    "fig_gold_standard_chimera",
    "fig_statistical_summary",
    "generate_all_figures",
    "table_ablation_variants",
    "table_parameter_efficiency",
    "table_chimera_gold_standard",
    "table_statistical_summary",
    "table_occlusion_sweep",
    "table_oscillosim_scaling",
    "generate_all_tables",
    "SCALROptimizer",
    "RIPOptimizer",
    "SynchronizedGradientDescent",
    "TemporalPhasePropagator",
    "temporal_recovery_speed",
    "OscillatorModel",
    "ThetaGammaNetwork",
    "DeltaThetaGammaNetwork",
    "BackendUnavailableError",
    "triton_available",
    "triton_fused_mean_field_rk4_step",
    "triton_sparse_knn_coupling",
    "triton_pac_modulation",
    "triton_hierarchical_order_param",
    "triton_fused_discrete_step",
    "cuda_fused_kernel_available",
    "fused_discrete_step_cuda",
    # WP-036 S1 sub-pass 0141B — prin-tensor (WP-014) + prin-train (WP-023)
    # bindings.
    "PolyadicTensor",
    "CPDecomposition",
    "dSiLU",
    "PhaseActivation",
    "HolomorphicActivation",
    "FeedbackInhibition",
    "HolomorphicEnergy",
    "HolomorphicEPTrainer",
    # WP-036 S1 sub-pass 0141C — Rust-owned CPU kernel/sweep compatibility.
    "pytorch_mean_field_rk4_step",
    "pytorch_sparse_knn_coupling",
    "pytorch_pac_modulation",
    "pytorch_hierarchical_order_param",
    "pytorch_multi_rate_rk4_step",
    "pytorch_multi_rate_derivatives",
    "pytorch_fused_sub_step_rk4",
    "pytorch_cross_band_coupling",
    "pytorch_fused_discrete_step",
    "pytorch_fused_discrete_step_full",
    "csr_coupling_step",
    "sparse_knn_coupling_step",
    "build_knn_neighbors",
    "sparse_coupling_matrix",
    "sparse_coupling_matrix_csr",
    "sweep_coupling_params",
    "detect_oscillation",
    "phase_to_rate",
    # WP-036 S1 sub-pass 0141D1 — net-new Python surface (Bucket G): solver
    # family over the Rust integrator owners + telemetry observation hook.
    "SolverResult",
    "BatchedRK45Solver",
    "FixedStepRK4Solver",
    "gradient_checkpoint_integration",
    "TelemetryLogger",
)
